// file: SaludOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package ontologisalud;

import jade.content.onto.*;
import jade.content.schema.*;
import jade.util.leap.HashMap;
import jade.content.lang.Codec;
import jade.core.CaseInsensitiveString;

/** file: SaludOntology.java
 * @author ontology bean generator
 * @version 2019/08/9, 02:09:47
 */
public class SaludOntology extends jade.content.onto.Ontology  {
  //NAME
  public static final String ONTOLOGY_NAME = "salud";
  // The singleton instance of this ontology
  private static ReflectiveIntrospector introspect = new ReflectiveIntrospector();
  private static Ontology theInstance = new SaludOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String ANALIZAR_PATOLOGIAS_INFORMACION_PULPITIS_IREVERSIBLE="Informacion_pulpitis_ireversible";
    public static final String ANALIZAR_PATOLOGIAS_INFORMACION_PULPITIS_REVERSIBLE="Informacion_pulpitis_reversible";
    public static final String ANALIZAR_PATOLOGIAS_INFORMACION_CARIES_INCIPIENTE="Informacion_caries_incipiente";
    public static final String ANALIZAR_PATOLOGIAS="Analizar_patologias";
    public static final String SOLICITAR_TRATAMIENTO_DESBRIDAMIENTO="Desbridamiento";
    public static final String SOLICITAR_TRATAMIENTO_TOPICACION_FLUOR="Topicacion_fluor";
    public static final String SOLICITAR_TRATAMIENTO_PROFILAXIS="Profilaxis";
    public static final String SOLICITAR_TRATAMIENTO="Solicitar_tratamiento";
    public static final String PULPITIS_REVERSIBLE_FISURA="Fisura";
    public static final String PULPITIS_REVERSIBLE_COLOR_OSCURO="Color_oscuro";
    public static final String PULPITIS_REVERSIBLE_CONTACTO_OCLUSION="Contacto_oclusion";
    public static final String PULPITIS_REVERSIBLE="Pulpitis_reversible";
    public static final String PULPITIS_IRREVERSIBLE_INFLAMACION_PULPAR="Inflamacion_pulpar";
    public static final String PULPITIS_IRREVERSIBLE_DOLOR_PROLONGADO="Dolor_prolongado";
    public static final String PULPITIS_IRREVERSIBLE_DOLOR_ESTIMULACION_EXTERNA="Dolor_estimulacion_externa";
    public static final String PULPITIS_IRREVERSIBLE="Pulpitis_irreversible";
    public static final String CARIES_INCIPIENTE_OPACIDAD_ESMALTE="Opacidad_esmalte";
    public static final String CARIES_INCIPIENTE_COLOR_BLANQUECINO="Color_blanquecino";
    public static final String CARIES_INCIPIENTE_BORDES_DEFINIDOS="Bordes_definidos";
    public static final String CARIES_INCIPIENTE="Caries_incipiente";

  /**
   * Constructor
  */
  private SaludOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema caries_incipienteSchema = new ConceptSchema(CARIES_INCIPIENTE);
    add(caries_incipienteSchema, ontologisalud.Caries_incipiente.class);
    ConceptSchema pulpitis_irreversibleSchema = new ConceptSchema(PULPITIS_IRREVERSIBLE);
    add(pulpitis_irreversibleSchema, ontologisalud.Pulpitis_irreversible.class);
    ConceptSchema pulpitis_reversibleSchema = new ConceptSchema(PULPITIS_REVERSIBLE);
    add(pulpitis_reversibleSchema, ontologisalud.Pulpitis_reversible.class);

    // adding AgentAction(s)

    // adding AID(s)

    // adding Predicate(s)
    PredicateSchema solicitar_tratamientoSchema = new PredicateSchema(SOLICITAR_TRATAMIENTO);
    add(solicitar_tratamientoSchema, ontologisalud.Solicitar_tratamiento.class);
    PredicateSchema analizar_patologiasSchema = new PredicateSchema(ANALIZAR_PATOLOGIAS);
    add(analizar_patologiasSchema, ontologisalud.Analizar_patologias.class);


    // adding fields
    caries_incipienteSchema.add(CARIES_INCIPIENTE_BORDES_DEFINIDOS, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    caries_incipienteSchema.add(CARIES_INCIPIENTE_COLOR_BLANQUECINO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    caries_incipienteSchema.add(CARIES_INCIPIENTE_OPACIDAD_ESMALTE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    pulpitis_irreversibleSchema.add(PULPITIS_IRREVERSIBLE_DOLOR_ESTIMULACION_EXTERNA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    pulpitis_irreversibleSchema.add(PULPITIS_IRREVERSIBLE_DOLOR_PROLONGADO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    pulpitis_irreversibleSchema.add(PULPITIS_IRREVERSIBLE_INFLAMACION_PULPAR, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    pulpitis_reversibleSchema.add(PULPITIS_REVERSIBLE_CONTACTO_OCLUSION, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    pulpitis_reversibleSchema.add(PULPITIS_REVERSIBLE_COLOR_OSCURO, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    pulpitis_reversibleSchema.add(PULPITIS_REVERSIBLE_FISURA, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    solicitar_tratamientoSchema.add(SOLICITAR_TRATAMIENTO_PROFILAXIS, pulpitis_reversibleSchema, ObjectSchema.OPTIONAL);
    solicitar_tratamientoSchema.add(SOLICITAR_TRATAMIENTO_TOPICACION_FLUOR, caries_incipienteSchema, ObjectSchema.OPTIONAL);
    solicitar_tratamientoSchema.add(SOLICITAR_TRATAMIENTO_DESBRIDAMIENTO, pulpitis_irreversibleSchema, ObjectSchema.OPTIONAL);
    analizar_patologiasSchema.add(ANALIZAR_PATOLOGIAS_INFORMACION_CARIES_INCIPIENTE, caries_incipienteSchema, ObjectSchema.OPTIONAL);
    analizar_patologiasSchema.add(ANALIZAR_PATOLOGIAS_INFORMACION_PULPITIS_REVERSIBLE, pulpitis_reversibleSchema, ObjectSchema.OPTIONAL);
    analizar_patologiasSchema.add(ANALIZAR_PATOLOGIAS_INFORMACION_PULPITIS_IREVERSIBLE, pulpitis_irreversibleSchema, ObjectSchema.OPTIONAL);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
  }
